nodo_balanza:
  ros__parameters:
    hx711_reference_unit: 2273.9

nodo_camara:
  ros__parameters:
    device_index: 0
    recortar_ojo_izquierdo: true
    redimensionar: true
    ancho_objetivo: 640
    alto_objetivo: 480
    rotar_90_horario: true
    distancia_camara_cm: 60.0

nodo_actuadores:
  ros__parameters:
    tiempo_motor: 3.8

nodo_vision:
  ros__parameters:
    roi_x: 0
    roi_y: 0
    roi_w: 480
    roi_h: 640
